INSERT INTO department (name)
VALUES ("Sales and Marketing"),
       ("IT"),
       ("Legal"),
       ("Accounting"),
       ("Purchasing"),
       ("HR"),
       ("Production");

INSERT INTO role (department_id, title, salary)
VALUES (1, "Sales Person", 60000),
       (1, "Sales Manager", 90000),
       (1, "Market Analyst", 60000),
       (1, "Senior Market Analyst", 75000),
       (1, "Marketing Manager", 90000),
       (2, "Programer", 60000),
       (2, "Senior Programer", 75000),
       (2, "IT Manager", 90000),
       (3, "Paralegal", 60000),
       (3, "Counsel", 90000),
       (3, "Chief Legal Counsel", 150000),
       (4, "Financial Analyst", 60000),
       (4, "Accounting Manager", 90000),
       (4, "CFO", 250000),
       (5, "Procurement Specialist", 60000),
       (5, "Supply Chain Manager", 90000),
       (6, "HR Coordinator", 60000)
       (6, "HR Manager", 90000),
       (7, "Line Employee", 45000),
       (7, "Line Manager", 60000),
       (7, "Production Manager", 90000);
       (7, "COO", 250000),
       
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Michael", "Garrigus", 1),
       ("Marcus", "Gambia", 2),
       ("Al", "Smith", 3),
       ("Charles", "Ivery", 4),
       ("Edward", "Zea", 5),
       ("Edward", "Walsh", 6),
       ("Frederic", "Plummer", 7),
       ("Gustav", "Moser", 8),
       ("Jhonny", "Valle", 9),
       ("Joseph", "Vizcaya", 10),
       ("Lauren", "Marlow", 11),
       ("Maurizio", "Acquavella", 12),
       ("Raphale", "Benclaire", 13),
       ("Richard", "Behr", 14),
       ("Wolfgang", "Van Halen", 15),
       ("Clio", "Knowles", 1),
       ("Charleen", "Doe", 16),
       ("Jane", "Applesmith", 17),
       ("Emma", "Moose", 18),
       ("Jessica", "Morgan", 19),
       ("Morgan", "Gill", 20),
       ("Shawn", "Muller", 21),
       ("Trey", "Johnson", 22),
       ("John", "Treyson", 1),

