INSERT INTO department (name)
VALUES ("Sales and Marketing"),
       ("IT"),
       ("Legal"),
       ("Accounting"),
       ("Purchasing"),
       ("HR"),
       ("Production");

INSERT INTO role (department_id, title, salary)
VALUES (1, "Sales Person", 60000),
       (1, "Sales Manager", 90000),
       (1, "Market Analyst", 60000),
       (1, "Senior Market Analyst", 75000),
       (1, "Marketing Manager", 90000),
       (2, "Programmer", 60000),
       (2, "Senior Programmer", 75000),
       (2, "IT Manager", 90000),
       (3, "Paralegal", 60000),
       (3, "Counsel", 90000),
       (3, "Chief Legal Counsel", 150000),
       (4, "Financial Analyst", 60000),
       (4, "Accounting Manager", 90000),
       (4, "CFO", 250000),
       (5, "Procurement Specialist", 60000),
       (5, "Supply Chain Manager", 90000),
       (6, "HR Coordinator", 60000), -- Added comma here
       (6, "HR Manager", 90000),
       (7, "Line Employee", 45000),
       (7, "Line Manager", 60000),
       (7, "Production Manager", 90000),
       (7, "COO", 250000); -- Removed extra comma here

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Michael", "Garrigus", 1, null),
       ("Marcus", "Gambia", 2, null),
       ("Al", "Smith", 3, null),
       ("Charles", "Ivery", 4, null),
       ("Edward", "Zea", 5, null),
       ("Edward", "Walsh", 6, null),
       ("Frederic", "Plummer", 7, null),
       ("Gustav", "Moser", 8, null),
       ("Jhonny", "Valle", 9, null),
       ("Joseph", "Vizcaya", 10, null),
       ("Lauren", "Marlow", 11, null),
       ("Maurizio", "Acquavella", 12, null),
       ("Raphale", "Benclaire", 13, null),
       ("Richard", "Behr", 14, null),
       ("Wolfgang", "Van Halen", 15, null),
       ("Clio", "Knowles", 1, null),
       ("Charleen", "Doe", 16, null),
       ("Jane", "Applesmith", 17, null),
       ("Emma", "Moose", 18, null),
       ("Jessica", "Morgan", 19, null),
       ("Morgan", "Gill", 20, null),
       ("Shawn", "Muller", 21, null),
       ("Trey", "Johnson", 22, null),
       ("John", "Treyson", 1, null);